logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s.%(msecs)03d|%(levelname)-8s|%(name)40s:%(lineno)-4s|%(funcName)-35s|%(message)s'
      datefmt: '%Y.%m.%d-%H:%M:%S'
  handlers:
    stdout_console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.handlers.FileHandler
      level: DEBUG
      formatter: simple
      filename: experiment.log
      encoding: utf8
  root:
    level: DEBUG
    handlers:
      - stdout_console
      - file
